#!/usr/bin/python

import MySQLdb
import os,sys,time
pwd=os.popen('cat /usr/local/opencdn/conf/opencdn.conf | grep DB_PassWord | awk -F= \'{print $2}\'').read()
db=MySQLdb.connect('127.0.0.1','root',pwd[:-1],'cdn_info')
print 'Database connected.'
cur=db.cursor()
while 1:
	cur.execute("select NodeIP from node_info;")
	rows=cur.fetchall()
	for i in range(0,len(rows)):
		wget_cmd='wget -t 1 -T 1 '+rows[i][0]+'/node.txt -O result.txt > /dev/null 2>&1'
		os.popen(wget_cmd)
		is_wget_exsist = os.popen("cat result.txt").read()
		if (is_wget_exsist):
			print rows[i][0]+' is up'
			cur.execute("update node_info set Status='on' where NodeIP='"+rows[i][0]+"';")
		else:
			ping_cmd='ping -W 3 -c 2 '+rows[i][0]
			is_ping_exsist = os.popen(ping_cmd).read()
			if (is_ping_exsist.find("time=")!=-1):
				print rows[i][0]+' is up'
				cur.execute("update node_info set Status='on' where NodeIP='"+rows[i][0]+"';")
			else:
				print rows[i][0]+' is down.'
				cur.execute("update node_info set status='off' where NodeIP='"+rows[i][0]+"';")
	time.sleep(5)
